### ISSUE TITLE
Tests fail to build on glibc>=2.34 (Ubuntu 22.04)

### ISSUE THREAD

**Issue by ekilmer** [lifting-bits/remill#635]
`SIGSTKSZ` is no longer constant
https://sourceware.org/git/?p=glibc.git;a=blob;f=NEWS;h=865157146427eff9819386eb5237900b0a6260be;hb=refs/heads/release/2.34/master#l149

Discovered when trying to build with Ubuntu 22.04 in https://github.com/lifting-bits/cxx-common/pull/970
```
/__w/cxx-common/cxx-common/remill/tests/X86/Run.cpp:55:11: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
  uint8_t bytes[(SIGSTKSZ / 128) * 128];
          ^
```
